# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e88e74dc5bc78d7048f58041ee2977e8f344ac4b1ec844e9b3f72b8c4c4a33752a4eb6875349f195c533d82cab01a34c3f87ee5d624755a16ac0667d170a22

test:
  secret_key_base: 979d72f28b8d068f5d490af9466510f7773130be85c39780ae18a534fbe15c1458264c90328547f2b070fdb73dd7f4b896cd156311c01424b160c76b284d94b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
